#! /usr/bin/bash

###############################################################################################
# Author:
#	brown.liuzan
# Copyright owner:
#	brown.liuzan
# Email:
#	brown.liuzan@outlook.com
# Description:
#	1) Configure bash.
#	2) Configure vim.
#	3) Configure git.
###############################################################################################

source lib/errno.sh
source lib/environments.sh
source lib/printer.sh

function usage()
{
	print_bold_green "Usage:"
	print_green "\t$0 [-h|--help]"
	print_bold_green "Examples:"
	print_green "1) a complete setup"
	print_green "\t$0"
	print_green "2) show this help info"
	print_green "\t$0 -h"
}

function config_bash() {
	print_green "========configure bash: begin========"
	if [[ -f /etc/profile.d/brown_liuzan_bash_config.sh ]]; then
		rm -f /etc/profile.d/brown_liuzan_bash_config.sh.bak
		mv /etc/profile.d/brown_liuzan_bash_config.sh  \
			/etc/profile.d/brown_liuzan_bash_config.sh.bak
	fi
	cp brown_liuzan_bash_config.sh /etc/profile.d/brown_liuzan_bash_config.sh
	source /etc/profile.d/brown_liuzan_bash_config.sh
	print_green "========configure bash: end========"
	echo
}

function config_cscope() {
	print_green "========configure cscope: begin========"
	local vVerInfo=$(cscope --version)
	vRc=$?
	if [[ ${vRc} -eq 0 ]]; then
		print_white "${vVerInfo}"
		return
	fi
	case ${OS_ID} in
	'centos' | 'rocky' | 'fedora')
		yum install -y cscope
		;;
	'debian' | 'ubuntu')
		apt install -y cscope
		;;
	*)
		print_red "Unsupported OS: ${OS_ID}"
		;;
	esac
	print_green "========configure cscope: end========"
}

function config_vim() {
	print_green "========configure vim: begin========"
	if [[ ! -d /repo/CscopeAndCtags ]]; then
		mkdir -p /repo/CscopeAndCtags
	fi
	if [[ -f /root/.vimrc ]]; then
		rm -f /root/.vimrc.bak
		mv /root/.vimrc /root/.vimrc.bak
	fi
	cp vimrc.template /root/.vimrc
	print_green "========configure vim: end========"
	echo
}

function config_git() {
	print_green "========configure git: begin========"
	git config --global core.editor 'vim'
	git config --global user.name 'brown.liuzan'
	git config --global user.email 'brown.liuzan@outlook.com'
	git config --global push.default 'simple'
	git config --global --list
	print_green "========configure git: end========"
	echo
}

function main() {
	for((i = 1; i <= $#; ++i)); do
		case ${!i} in
		'-h' | '--help')
			usage $0
			exit $EOK
			;;
		*)
			usage $0
			exit $EINVAL
			;;
		esac
	done

	config_bash
	config_cscope
	config_vim
	config_git
}

main "$@"
